config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :crazycatladies
    root "crazycatladies#index"
  #
  resources :cats

  # resources :cats
  #   root "crazycatladies#index"
  # #
  # resources :crazycatladies


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord

  belongs_to :crazycatlady

end

app/models/crazy_cat_lady.rb
class CrazyCatLady < ApplicationRecord

  has_many :cats

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



end

app/controllers/crazycatladies_controller.rb
class CrazycatladiesController < ApplicationController

def index
  @crazy_cat_lady = CrazyCatLady.all
end

def show
  @crazy_cat_lady = CrazyCatLady.find(params[:id])
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/crazycatladies/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>CrazyCatLadies</h1>
  <nav>
      <ul>
        <li>home</li>
        <li>ladies</li>
        <li>new</li>
      </ul>
    </nav>


<div class="lady">
      <li class="lady">
        <% @crazy_cat_lady.each do |crazycatlady| %>
        <%= image_tag crazycatlady.image_url %>
      </li>
      <li class="lady">
    <%= link_to crazycatlady.name, crazycatlady_path(crazycatlady.id) %>
  </li>
    <% end %>
</div>

</body>
</html>

app/views/crazycatladies/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

  <h1><%= @crazy_cat_lady.name %></h1>

  <p>Age: <%= @crazy_cat_lady.age %></p>

  <%= image_tag @crazy_cat_lady.image_url %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrazyCatLadies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>